name: Deploy to Azure VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      run: |
        apt-get install -y openssh-client && apt-get clean

        echo "ssh-keyscan to known_hosts"
        ssh-keyscan -H "${{ secrets.AZURE_VM_HOST }}" >> /tmp/known_hosts
        chmod 400 "${{ secrets.AZURE_VM_SSH_KEY }}" # stored as file

        ssh -o StrictHostKeyChecking=no -i "${{ secrets.AZURE_VM_SSH_KEY }}" "${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}" " &&

        docker stop express-containerized || true &&
        docker rm express-containerized || true &&
        docker pull zeelz/express-containerized:${{ vars.IMAGE_TAG }} &&
        docker run -d -p 3000:3000 --name express-containerized --platform linux/amd64 -e "DB_USER=${{ vars.DB_USER }}" -e "DB_HOST=${{ vars.DB_HOST }}" -e "DB_NAME=postgres" -e "DB_PORT=${{ vars.DB_PORT }}" zeelz/express-containerized:${{ vars.IMAGE_TAG }} &&
        "